name: energized_id_server
description: The server for our ID-printing software.
version: 0.0.1
# author:

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  async: ^2.0.8
  aqueduct: ^3.0.0
  image: ^2.0.7
  path: ^1.6.2

  energized_id:
    git: https://github.com/energized-id/energized_id.git

dev_dependencies:
  aqueduct_test: ^1.0.0
  build_runner: ^1.2.0
  csv: ^4.0.3
  http: ^0.12.0
  pedantic: ^1.0.0
  test: ^1.0.0