name: energized_id_server
description: The server for our ID-printing software.
version: 0.0.1
# author:

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0

  energized_id:
    git: https://github.com/energized-id/energized_id.git

dev_dependencies:
  aqueduct_test: ^1.0.0
  build_runner: ^1.2.0
  pedantic: ^1.0.0
  test: ^1.0.0